name: mp_audio_stream
description: A simple multi-platform audio stream player for raw audio data streams.
version: 0.1.5
repository: https://github.com/nortio/mp-audio-stream

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ffigen: ^10.0.0

ffigen:
  name: 'AudioStreamNative'
  description: 'Audio native module'
  output: 'lib/gen/mp_audio_stream.dart'
  headers:
    entry-points:
      - 'src/mp_audio_stream.h'
    include-directives:
      - 'src/mp_audio_stream.h'

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
