name: mp_audio_stream
description: A simple multi-platform audio stream player for raw audio data streams.
version: 0.1.5
repository: https://github.com/nortio/mp-audio-stream

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:

  assets:
    - packages/mp_audio_stream/js/audio_stream.js
